// English content preserved from audited commit 76877a4. Claims not re-researched.
const DISCLAIMER_EN = "Information contained in this document should not be construed as legal, tax, investment, financial, or other advice. Prospective donor investors are strongly encouraged to consult with their own accounting, tax, and financial professionals regarding the potential implications and suitability of any investment or transaction described.";
export const EN = {
  nav: {
    history: "History",
    property: "Property",
    investment: "Investment",
    kelly: "Kelly",
    cta: "Speak with Kelly",
  },
  hero: {
    location: "Coral Gables, Florida",
    price: "$3,200,000",
    h1a: "Five independent Cottages",
    h1b: "in a 13,140 sqft lot.",
    h1c: "First time on the market in two decades.",
    sub: "A 1929 historic estate. Five oolitic coral stone structures.",
    ctaPrimary: "Speak with Kelly Belem",
    ctaSecondary: "Discover the property →",
    rail1: "Vol. I · 2026 Edition",
    rail2: "1301 Milan Avenue",
    rail3: "Local Historic Landmark",
  },
  history: {
    eyebrow: "§ 02 · The History",
    h2a: "Built in 1929",
    h2b: "for the University",
    h2c: "of Miami.",
    p1: "Warren Zinsmaster purchased Madrid House directly from George Merrick's development team in 1924. Four years later, he commissioned architect E. Dean Parmelee to expand the compound into five oolitic coral stone structures, originally conceived to house visiting professors of the newly founded University of Miami. Zinsmaster later became the institution's first controller and accounting professor. The initials he carved into the doors and plaques of each cottage remain intact to this day, offering a lasting connection to the property's origins.",
    p2: "By the 2000s, the compound had already stood for over seven decades, carrying with it a rich architectural and historical legacy. In 2007, the property was officially designated as a Local Historic Landmark by the Coral Gables Historic Preservation Board.",
  },
  property: {
    eyebrow: "§ 03 · The Property",
    h2a: "Five independent historical cottages",
    h2b: "in the heart of",
    h2c: "Coral Gables.",
  },
  cottages: [
    { id: "c1", name: "Cottage 1", meta: "677 sq.ft. · 1 bed · 1 bath",
      body: "677 sq.ft. · 1 bed · 1 bath · kitchenette · walking closet · sitting area · private porch." },
    { id: "c2", name: "Cottage 2", meta: "677 sq.ft. · 1 bed · 1 bath",
      body: "677 sq.ft. · 1 bed · 1 bath · kitchenette · walking closet · sitting area · private porch." },
    { id: "c3", name: "Cottage 3", meta: "677 sq.ft. · 1 bed · 1 bath",
      body: "677 sq.ft. · 1 bed · 1 bath · kitchenette · walking closet · sitting area · private porch." },
    { id: "c4", name: "Cottage 4", meta: "677 sq.ft. · 1 bed · 1 bath",
      body: "677 sq.ft. · 1 bed · 1 bath · kitchenette · walking closet · sitting area · private porch." },
    { id: "c5", name: "Cottage 5", meta: "804 sq.ft. · 2 bed · 2 bath",
      body: "804 sq.ft. · 2 bed · 2 bath · kitchen · living room · closet." },
    { id: "ruina", name: "The Common Areas", meta: "Coral stone arcades · Rooftop terrace",
      body: "The common areas, framed by coral stone arcades and garden courtyards, transport you to another era. A rooftop terrace inspired by Park Güell in Barcelona offers a unique setting, perfect for intimate gatherings and memorable events. An additional structure, approved for restoration, presents endless possibilities as a media room, studio, event space, or even another private cottage." },
  ],
  tax: {
    eyebrow: "§ 04 · Tax Benefits of Historic Properties",
    h2a: "U.S. historic property",
    h2b: "has its own tax regime.",
    sub: "Timeless character with meaningful financial advantages.",
    body: "Owning a historic property offers not only timeless character, but also meaningful financial advantages.\n\nDesignated historic homes may qualify for property tax incentives, including partial exemptions on the value of approved improvements. These programs help reduce the overall tax burden while preserving the property's original integrity.\n\nIn some cases, restoration work may also be eligible for additional tax benefits, depending on local guidelines.\n\nBeyond the financial aspect, historic properties tend to hold long-term value due to their uniqueness and limited availability — making them both a lifestyle choice and a strategic investment.",
    disclaimer: DISCLAIMER_EN,
  },
  invest: {
    eyebrow: "§ 05 · Income-Generating Opportunity",
    h2a: "Five units.",
    h2b: "Multiple revenue streams.",
    body: "This property presents a compelling opportunity for those seeking both cultural richness and return on investment.\n\nWith the ability to be rented for periods of six months or longer, it offers a steady and reliable income stream while maintaining flexibility for personal use. Whether positioned as a seasonal residence or a long-term rental, the property is especially appealing to tenants who value art, history, and architectural character.\n\nIts versatility allows owners to maximize occupancy and generate consistent revenue, making it an ideal option for investors or buyers looking to offset ownership costs.\n\nA rare combination of heritage and performance, where your property works for you.",
    disclaimer: DISCLAIMER_EN,
  },
  kelly: {
    eyebrow: "§ 06 · Who represents this property",
    name: "Kelly Belem.",
    sub: "Top Producer · Master Agent · Agent of the Year — Keller Williams.",
    p1: "Born in Brazil and rooted in the United States, Kelly built her trajectory combining a decade of experience with multinational corporations — with a degree in Business and an MBA in Marketing — and the precision and discretion that the high-end real estate market demands. Her expertise in sales, strategic positioning, and product development transferred naturally to real estate, where she now represents buyers and sellers in high-value transactions across South Florida.",
    p2: "Recognized as a Top Producer in South Florida, and honored as both Master Agent and Agent of the Year at Keller Williams, Kelly has built a reputation grounded not only in results, but in the caliber of service she delivers. Her philosophy is simple yet uncompromising: every client is represented with intention, care, and a strategy tailored exclusively to their goals.",
    badges: ["Keller Williams Realty", "Top Producer · S. Florida", "Master Agent", "Agent of the Year"],
  },
  reviews: {
    eyebrow: "§ 07 · Google Reviews",
    h2a: "What clients say about",
    h2b: "Kelly Belem",
    items: [
      { name: "M & I", ctx: "Buyers · South Florida",
        quote: "Working with Kelly was both productive and enjoyable. She gave us full attention in every interaction, consistently going above and beyond. Competence, dedication, trust, and professionalism — truly a complete professional." },
      { name: "Sellers · 14940 Egan Lane", ctx: "Home sale in slow market",
        quote: "Within two weeks we had multiple offers and sold very close to the asking price. Kelly understands how to position and sell a home effectively, even in a slower market." },
      { name: "Buyers · 8787 SW 107th St", ctx: "Acquisition with custom payment structure",
        quote: "Kelly played a critical role in structuring our deal terms. Her ability to anticipate challenges gave us tremendous peace of mind." },
    ],
  },
  contact: {
    eyebrow: "§ 08 · Speak with Kelly",
    title: "The Coral Rock Village",
    address: "1301 Milan Avenue · Coral Gables",
    price: "$3,200,000",
    included: "What's included",
    bullets: [
      "Four Cottages — 677 sq.ft. each, in oolitic coral stone",
      "Cottage #5 — 804 sq.ft. + approved 1,000 sq.ft. expansion",
      "Historical Structure — multi-possibilities space, approved for restoration",
      "13,140 sq.ft. lot",
      "Local Historic Landmark designation",
    ],
    formTitle: "Fill out to speak with Kelly:",
    fields: { name: "Full name", email: "E-mail", phone: "Phone (with country code)" },
    submit: "Speak with Kelly Belem",
    whatsapp: "or open directly on WhatsApp →",
    waMsg: "Hello, I'm coming from the website and I'd like to talk about The Coral Rock Village.",
  },
  footer: { rights: "© 2026 · 1301 Milan Avenue · Coral Gables, FL" },
};
