import Link from 'next/link';
import {EN as t} from './coralrock-content';
import type {Development} from '@/lib/content/models';
import {Photo,SectionHeading} from '@/components/editorial';
import {MediaGallery} from '@/components/media-gallery';
import {LeadForm} from '@/features/forms/LeadForm';
const media='/media/coralrock/';
const galleries:Record<string,string[]>={c1:['cottage1-a.jpg'],c2:['cottage2-a.jpg','cottage2-b.jpg','cottage2-c.jpg','cottage2-d.jpg'],c3:['cottage3-a.jpg','cottage3-b.jpg','cottage3-c.jpg','cottage3-d.jpg'],c4:['cottage4-a.jpg','cottage4-b.jpg','cottage4-c.jpg','cottage4-d.jpg'],c5:['cottage5-a.jpg','cottage5-b.jpg','cottage5-c.jpg','cottage5-d.jpg','cottage5-e.jpg'],ruina:['ruina.webp','ruina-a.jpg','ruina-b.jpg','ruina-c.jpg','ruina-d.jpg','ruina-e.jpg','ruina-f.jpg','ruina-g.jpg','ruina-h.jpg','ruina-i.jpg','ruina-j.jpg']};
export function CoralRock({development:d}:{development:Development}){
 return <div className="coralrock"><nav className="coral-nav" aria-label="Coral Rock sections"><Link href="/">Kelly Belem ↖</Link><a href="#historia">History</a><a href="#propriedade">Property</a><a href="#investimento">Investment</a><a href="#contato">Contact</a></nav><section className="coral-hero" id="top"><Photo media={d.hero} priority sizes="100vw"/><div className="coral-hero-copy"><p className="eyebrow">The Coral Rock Village · Coral Gables · {d.commercialInformation.displayPrice}</p><h1>{t.hero.h1a}<br/>{t.hero.h1b}</h1><p>{t.hero.h1c}</p><p>{t.hero.sub}</p><a className="button light" href="#contato">Speak with Kelly Belem ↗</a></div></section><div className="press-rail"><span>Reuters</span><span>Associated Press</span><span>HGTV</span><span>Art Basel</span><span>Coral Gables Historic Preservation Board</span></div>
 <section id="historia" className="section container coral-history"><div><p className="eyebrow">{t.history.eyebrow}</p><h2>{t.history.h2a}<br/>{t.history.h2b}<br/>{t.history.h2c}</h2></div><div><p>{t.history.p1}</p><p>{t.history.p2}</p></div></section>
 <section className="section paper"><div className="container"><SectionHeading eyebrow="A closer look" title="Experience the village."/><video className="coral-video" controls playsInline preload="none" poster={d.video?.poster} aria-label="Coral Rock property tour"><source src={d.video?.src} type="video/mp4"/>Your browser does not support this property video.</video><p className="small mt-4">Property tour · The Coral Rock Village, 1301 Milan Avenue</p></div></section>
 <section id="propriedade" className="section beige"><div className="container"><SectionHeading eyebrow={t.property.eyebrow} title={t.property.h2a+' '+t.property.h2b+' '+t.property.h2c}/><div className="cottage-grid">{t.cottages.map(c=><article key={c.id}><MediaGallery images={galleries[c.id].map(f=>media+f)} label={c.name}/><div className="cottage-caption"><h3>{c.name}</h3><span>{c.meta}</span></div><p>{c.body}</p></article>)}</div></div></section>
 <section className="section dark-section"><div className="container"><p className="eyebrow">{t.tax.eyebrow}</p><div className="prose"><h2>{t.tax.h2a}<br/>{t.tax.h2b}</h2><p className="intro">{t.tax.sub}</p>{t.tax.body.split('\n\n').map(p=><p key={p}>{p}</p>)}<p className="legacy-disclaimer">{t.tax.disclaimer}</p></div></div></section>
 <section id="investimento" className="section container"><p className="eyebrow">{t.invest.eyebrow}</p><div className="prose"><h2>{t.invest.h2a} {t.invest.h2b}</h2>{t.invest.body.split('\n\n').map(p=><p key={p}>{p}</p>)}<p className="legacy-disclaimer">{t.invest.disclaimer}</p></div></section>
 <section id="kelly" className="section beige"><div className="container about-teaser"><MediaGallery images={['kelly.jpg','kelly-award-1.jpg','kelly-award-2.jpg'].map(f=>media+f)} label="Kelly Belem"/><div><p className="eyebrow">{t.kelly.eyebrow}</p><h2>{t.kelly.name}</h2><p>{t.kelly.sub}</p><p>{t.kelly.p1}</p><p>{t.kelly.p2}</p></div></div></section>
 <section className="section container"><SectionHeading eyebrow={t.reviews.eyebrow} title={t.reviews.h2a+' '+t.reviews.h2b}/><div className="grid-cards three">{t.reviews.items.map(r=><figure className="review-card" key={r.name}><blockquote>“{r.quote}”</blockquote><figcaption>{r.name}<span>{r.ctx}</span></figcaption></figure>)}</div></section>
 <section id="contato" className="section beige"><div className="container contact-grid"><div><p className="eyebrow">{t.contact.eyebrow}</p><h2>{t.contact.title}</h2><p className="intro mt-5">{t.contact.address}</p><p className="development-price">{d.commercialInformation.displayPrice}</p><p className="eyebrow mt-8">{t.contact.included}</p><ul className="list-disc pl-5 space-y-3">{t.contact.bullets.map(b=><li key={b}>{b}</li>)}</ul></div><LeadForm source="coralrock"/></div></section></div>;
}
