'use client';
import Link from 'next/link';
import {useState} from 'react';
import type {FormEvent} from 'react';
import type {Listing,SearchFilters} from '../types';
import {defaultFilters} from '../adapters/mock';
import {propertySearch} from '../api';
import {analytics} from '@/lib/analytics';
export function PropertyCard({listing:p}:{listing:Listing}){
 const [expanded,setExpanded]=useState(false);
 return <article className="property-card"><div className={'property-sketch sketch-'+p.type} aria-hidden><div className="sketch-roof"/><div className="sketch-building"><i/><i/><i/></div><span>Illustrative residence</span></div><div className="card-body"><p className="eyebrow">{p.location} · Fictional example</p><h2>{p.title}</h2><p className="property-price">{new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(p.price)}{p.transaction==='rent'?' / month':''}</p><p className="small">{p.beds} beds · {p.baths} baths · {p.area.toLocaleString('en-US')} sq.ft.</p><button className="text-link" aria-expanded={expanded} onClick={()=>{setExpanded(!expanded);if(!expanded)analytics.track('view_property',{property_id:p.id,page_type:'property-search'})}}>{expanded?'Close details −':'Explore this example +'}</button>{expanded&&<div className="property-detail"><p>{p.address} · {p.mlsNumber}</p><p>This fictional property demonstrates the search experience. It is not an available listing.</p><Link className="text-link" href="/contact">Discuss your search ↗</Link></div>}</div></article>;
}
export function PropertySearch({initialQuery='',initialTransaction='sale',initialListings=[]}:{initialQuery?:string;initialTransaction?:'sale'|'rent';initialListings?:Listing[]}){
 const [filters,setFilters]=useState<SearchFilters>({...defaultFilters,query:initialQuery,transaction:initialTransaction}),[results,setResults]=useState<Listing[]>(initialListings),[status,setStatus]=useState(initialListings.length+' fictional properties found.'),[loading,setLoading]=useState(false);
 const update=(key:keyof SearchFilters,value:string|number|boolean)=>setFilters(f=>({...f,[key]:value}));
 async function search(e?:FormEvent){e?.preventDefault();if(loading)return;if(filters.maxPrice&&filters.maxPrice<filters.minPrice){setStatus('Maximum price must be greater than minimum price.');return;}setLoading(true);try{const result=await propertySearch.search(filters);setResults(result.listings);setStatus(result.total+' fictional properties found.');analytics.track('property_search',{page_type:'property-search',result_count:result.total});}catch{setStatus('Unable to load examples. Please try again.');}finally{setLoading(false);}}
 return <><p className="preview-note">Search preview · All listings, prices and addresses below are fictional. No MLS connection.</p><form className="property-filters" onSubmit={search}><label className="field query-field"><span>Location, neighborhood, address or MLS number</span><input value={filters.query} onChange={e=>update('query',e.target.value)} placeholder="Try Coral Gables, Pinecrest or DEMO001"/></label><label className="field"><span>Sale / Rent</span><select value={filters.transaction} onChange={e=>update('transaction',e.target.value)}><option value="sale">For sale</option><option value="rent">For rent</option></select></label><label className="field"><span>Minimum price ($)</span><input type="number" min="0" step="1" value={filters.minPrice||''} onChange={e=>update('minPrice',Number(e.target.value))} placeholder="Any"/></label><label className="field"><span>Maximum price ($)</span><input type="number" min="0" step="1" value={filters.maxPrice||''} onChange={e=>update('maxPrice',Number(e.target.value))} placeholder="Any"/></label>{(['beds','baths'] as const).map(key=><label key={key} className="field"><span>{key==='beds'?'Bedrooms':'Bathrooms'}</span><select value={filters[key]} onChange={e=>update(key,Number(e.target.value))}><option value="0">Any</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n}+</option>)}</select></label>)}<label className="field"><span>Property type</span><select value={filters.type} onChange={e=>update('type',e.target.value)}><option value="">Any type</option><option value="house">House</option><option value="condo">Condo</option><option value="townhouse">Townhouse</option></select></label><label className="field"><span>Sort by</span><select value={filters.sort} onChange={e=>update('sort',e.target.value)}><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option></select></label><details className="extra-filters"><summary>Additional filters</summary><label className="check-label"><input type="checkbox" checked={filters.pool} onChange={e=>update('pool',e.target.checked)}/> Pool</label></details><div className="filter-actions"><button className="button" disabled={loading}>{loading?'Searching…':'Search examples'} ↗</button><button className="text-link" type="button" onClick={async()=>{setFilters({...defaultFilters});setResults((await propertySearch.search(defaultFilters)).listings);setStatus('Filters cleared. Showing all sale examples.')}}>Clear filters</button></div></form><p className="search-status" role="status">{status}</p>{results.length>0?<div className="grid-cards three">{results.map(p=><PropertyCard key={p.id} listing={p}/>)}</div>:<div className="empty-state"><h2>A different starting point.</h2><p>Try a broader location or adjust the price and room filters.</p><Link className="text-link" href="/contact">Talk through your priorities ↗</Link></div>}</>;
}
