import Link from 'next/link';
import {cms} from '@/lib/cms';
import {metadataFor,personSchema} from '@/lib/seo';
import {JsonLd,Photo,SectionHeading,AdvisoryCard,DevelopmentCard,NeighborhoodCard,ArticleCard,ResourceCard,ContactCTA} from '@/components/editorial';
import {PropertySearchBar} from '@/features/property-search/components/PropertySearchBar';

export const metadata=metadataFor({title:'Miami Real Estate Advisor',description:'A thoughtful approach to buying, selling and owning real estate in Coral Gables, Pinecrest and South Florida.'},'/');

export default async function Home(){
 const [developments,neighborhoods,posts,resources]=await Promise.all([cms.developments(),cms.neighborhoods(),cms.posts(),cms.resources()]);
 return <>
  <JsonLd data={personSchema}/>
  <section className="home-hero immersive-hero">
   <Photo media={{src:'/media/kelly/entrance.jpg',alt:'Kelly Belem at the entrance of a contemporary South Florida home'}} priority className="home-hero-media" sizes="100vw" parallax={.035}/>
   <div className="home-hero-shade" aria-hidden="true"/>
   <div className="home-hero-copy"><p className="eyebrow">Kelly Belem · Miami Real Estate Advisor</p><h1>Real estate.<br/><em>With perspective.</em></h1><p className="intro">A place to live. A new chapter. A considered investment. The right decision begins with understanding what matters to you.</p><div className="hero-actions"><Link href="/contact" className="button">Start a conversation <span aria-hidden>↗</span></Link><Link href="/property-search" className="text-link">Explore properties <span aria-hidden>↗</span></Link></div><div className="hero-footnote">Coral Gables · Pinecrest · South Florida</div></div>
   <span className="hero-photo-caption">People. Property. Perspective.</span>
  </section>
  <section className="section container philosophy-grid intro-panel"><p className="eyebrow">01 / A considered approach</p><div><h2>More than finding a property.<br/>Understanding the decision.</h2><p className="intro">A listing can show you the space. The right conversation brings the bigger picture into focus: the neighborhood, the timing, the possibilities and the life you want to build.</p><p className="philosophy-signature">Context first. Then, the right next step.</p></div></section>
  <section className="section beige service-section"><div className="container"><SectionHeading eyebrow="02 / Ways we can work together" title="Your priorities. A personal approach."/><div className="grid-cards three service-grid"><AdvisoryCard number="01" title="Buy" text="A thoughtful search, a considered shortlist and guidance through each decision." href="/buy" image={{src:'/media/kelly/standing.jpg',alt:'Kelly Belem standing in a tailored black outfit'}}/><AdvisoryCard number="02" title="Sell" text="Position your property with intention, a clear perspective and a tailored approach." href="/sell" image={{src:'/media/kelly/architecture.jpg',alt:'Kelly Belem in a warm architectural interior'}}/><AdvisoryCard number="03" title="Invest" text="Understand the property and the ownership picture, wherever your journey begins." href="/invest" image={{src:'/media/kelly/conversation.jpg',alt:'Kelly Belem in conversation at home'}}/></div></div></section>
  <section className="section journey-section"><div className="container journey-layout"><div className="journey-visual"><Photo media={{src:'/media/kelly/architecture.jpg',alt:'Kelly Belem in a considered South Florida interior'}} parallax={.02}/><span>Guidance beyond the search</span></div><div><SectionHeading eyebrow="03 / The decision journey" title="A little more clarity at every step."/><div className="journey">{[['Before the search','Clarify the purpose, priorities and practicalities.'],['Property selection','Compare the details that matter to your life.'],['The transaction','Navigate each step with a coordinated team.'],['After closing','Find your rhythm in a new chapter of ownership.']].map(([title,text],i)=><article key={title}><span className="index-number">0{i+1} ──</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></div></section>
  <section className="section container about-teaser about-early"><Photo media={{src:'/media/kelly/conversation.jpg',alt:'Kelly Belem seated in a warm contemporary interior'}}/><div><p className="eyebrow">04 / Meet Kelly</p><h2>A local perspective.<br/>An international understanding.</h2><p className="intro">Born in Brazil and based in South Florida, Kelly brings a thoughtful, personal approach to the decisions that shape where and how you live.</p><p className="intro">From your first questions to life after closing, the conversation stays centered on you.</p><Link href="/about" className="text-link">Get to know Kelly ↗</Link></div></section>
  <section className="search-section"><div className="container"><p className="eyebrow">05 / An informed starting point</p><h2>Find the property.<br/>Understand the decision.</h2><PropertySearchBar/><p className="small" id="property-search-help">Continue to the MLS search, then enter your location and filters there. Text entered here is not transferred.</p></div></section>
  <section className="section container development-feature"><SectionHeading eyebrow="06 / An exceptional address" title="A property with a story."/><DevelopmentCard item={developments[0]}/></section>
  <section className="section paper neighborhood-section"><div className="container"><SectionHeading eyebrow="07 / A sense of place" title="Find your South Florida." href="/neighborhoods" linkLabel="Explore neighborhoods"/><div className="neighborhood-grid">{neighborhoods.map(n=><NeighborhoodCard key={n.id} item={n}/>)}</div></div></section>
  <section className="section container insights-section"><SectionHeading eyebrow="08 / Perspectives & insights" title="Better questions. Better decisions." href="/blog" linkLabel="Read all insights"/><div className="insights-grid">{posts.slice(0,3).map((p,i)=><ArticleCard key={p.id} post={p} index={i}/>)}</div></section>
  <section className="section beige resources-section"><div className="container"><SectionHeading eyebrow="09 / The Kelly Belem guides" title="Clarity, one step at a time." href="/resources" linkLabel="Explore the guides"/><div className="grid-cards four resource-grid">{resources.map(r=><ResourceCard key={r.id} item={r}/>)}</div></div></section>
  <ContactCTA/>
 </>;
}
