import Link from 'next/link';
import Image from 'next/image';
import type {ReactNode} from 'react';
import type {Media,Post,Neighborhood,Development,Resource,ContentSection} from '@/lib/content/models';
import {siteUrl} from '@/lib/seo';
export function JsonLd({data}:{data:unknown}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data).replace(/</g,'\\u003c')}}/>}
export function Breadcrumbs({items}:{items:{label:string;href:string}[]}){
 const all=[{label:'Home',href:'/'},...items];
 return <><nav className="breadcrumbs" aria-label="Breadcrumb"><ol>{all.map((i,n)=><li key={i.href}>{n>0&&<span aria-hidden>/</span>}{n===all.length-1?<span aria-current="page">{i.label}</span>:<Link href={i.href}>{i.label}</Link>}</li>)}</ol></nav><JsonLd data={{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:all.map((i,n)=>({'@type':'ListItem',position:n+1,name:i.label,item:siteUrl+i.href}))}}/></>;
}
export function Photo({media,className='',priority=false,sizes='(max-width: 760px) 100vw, 50vw',parallax}:{media:Media;className?:string;priority?:boolean;sizes?:string;parallax?:number}){return <div className={'photo '+className} data-parallax={parallax}><Image src={media.src} alt={media.alt} fill sizes={sizes} preload={priority} className="object-cover"/></div>}
export function SectionHeading({eyebrow,title,children,href,linkLabel='Explore more'}:{eyebrow:string;title:string;children?:ReactNode;href?:string;linkLabel?:string}){return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{children&&<div className="section-description">{children}</div>}</div>{href&&<Link className="text-link" href={href}>{linkLabel} <span aria-hidden>↗</span></Link>}</div>}
export function EditorialHero({eyebrow,title,description,image,children}:{eyebrow:string;title:string;description:string;image?:Media;children?:ReactNode}){return <section className={'editorial-hero container '+(image?'with-image':'')}><div className="editorial-hero-copy"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="intro">{description}</p>{children}</div>{image&&<Photo media={image} priority className="hero-photo"/>}</section>}
export function ContactCTA(){return <section className="contact-cta"><div className="container"><p className="eyebrow">Your next chapter</p><h2>A considered decision.<br/>A personal conversation.</h2><Link className="button light" href="/contact">Let’s talk about your plans <span aria-hidden>↗</span></Link></div></section>}
export function AdvisoryCard({number,title,text,href,image}:{number:string;title:string;text:string;href:string;image?:Media}){return <article className="advisory-card" data-reveal>{image&&<Link href={href} tabIndex={-1} aria-hidden><Photo media={image} className="advisory-image" sizes="(max-width:760px) 100vw, 33vw"/></Link>}<div className="advisory-card-copy"><span className="index-number">{number}</span><h3>{title}</h3><p>{text}</p><Link className="text-link" href={href}>Explore {title.toLowerCase()} <span aria-hidden>↗</span></Link></div></article>}
export function ArticleCard({post,index=0}:{post:Post;index?:number}){const images=['/media/kelly/entrance.jpg','/media/kelly/conversation.jpg','/media/kelly/architecture.jpg','/media/kelly/portrait.jpg'];return <article className="article-card" data-reveal><Link href={'/blog/'+post.slug} tabIndex={-1} aria-hidden><Photo media={{src:images[index%4],alt:''}} className="article-image" sizes="(max-width:760px) 100vw, 33vw"/></Link><div className="article-card-copy"><p className="eyebrow">{post.categories[0]} · {post.readingMinutes} min read</p><h3><Link href={'/blog/'+post.slug}>{post.title}</Link></h3><p>{post.excerpt}</p><Link className="text-link" href={'/blog/'+post.slug} aria-label={'Read '+post.title}>Read the perspective ↗</Link></div></article>}
export function NeighborhoodCard({item}:{item:Neighborhood}){return <article className="neighborhood-card" data-reveal><Link href={'/neighborhoods/'+item.slug}>{item.image?<Photo media={item.image} className="neighborhood-image"/>:<div className="neighborhood-placeholder" aria-hidden><span>P</span></div>}<div className="neighborhood-caption"><div><p className="eyebrow">{item.eyebrow}</p><h3>{item.title}</h3></div><span aria-hidden>↗</span></div></Link></article>}
export function DevelopmentCard({item}:{item:Development}){return <article className="development-card" data-reveal><Photo media={item.hero} className="development-image" parallax={.025}/><div className="development-copy"><p className="eyebrow">Featured property · {item.location.city}</p><h2>{item.title}</h2><p>{item.overview}</p><div className="property-facts">{item.propertyDetails.map(f=><div key={f.label}><strong>{f.value}</strong><span>{f.label}</span></div>)}</div><p className="development-price">{item.commercialInformation.displayPrice}</p><Link className="button outline" href={'/'+item.slug}>Discover Coral Rock <span aria-hidden>↗</span></Link></div></article>}
export function ResourceCard({item}:{item:Resource}){return <article className="resource-card" data-access={item.access} data-reveal><Link href={'/blog/'+item.articleSlug} tabIndex={-1} aria-hidden><Photo media={item.cover} className="resource-image" sizes="(max-width:760px) 50vw, 25vw"/></Link><p className="eyebrow">The Kelly Belem guides</p><h3>{item.title}</h3><p>{item.description}</p><Link className="text-link" href={'/blog/'+item.articleSlug}>Read the guide ↗</Link>{item.download&&item.access==='open'&&<a className="text-link" href={item.download} download>Download PDF ↓</a>}{item.access==='gated'&&<Link className="text-link" href="/contact">Request this guide ↗</Link>}</article>}
export function QuoteBlock({quote,by}:{quote:string;by:string}){return <figure className="quote-block"><blockquote>{quote}</blockquote><figcaption>{by}</figcaption></figure>}
export function EditorialContent({sections}:{sections:ContentSection[]}){return <div className="prose">{sections.map(s=><section id={s.id} key={s.id}><h2>{s.heading}</h2>{s.paragraphs.map(p=><p key={p}>{p}</p>)}{s.bullets&&<ul>{s.bullets.map(b=><li key={b}>{b}</li>)}</ul>}</section>)}</div>}
export function AdSlotPlaceholder(){return <aside className="ad-slot" aria-label="Reserved editorial advertising space"><span>Editorial advertising space · Preview</span></aside>}
